baseURL = 'https://bearsbelly.github.io/.co'
languageCode = 'en-us'
title = 'Η Κοιλιά της Αρκούδας'
theme = 'ananke' # Theming needs more work
#
#
#
DefaultContentLanguage = "gr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false
#
#
#
[languages]
  [languages.en]
    title = "Bear's Belly Co."
    weight = 2
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.gr]
    title = "Η Κοιλιά της Αρκούδας"
    weight = 2
    contentDir = "content/gr"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "No more bs"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/bearsbellyq"

