baseURL = 'https://abstrart.github.io/bbq'
languageCode = 'en-us'
title = 'Η Κοιλιά της Αρκούδας'
theme = 'ananke1' # Theming needs more work
#
#
#
DefaultContentLanguage = "gr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false
#
#
#
[languages]
  #[languages.en]
    # title = "Ananke"
    # weight = 1
    # contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.gr]
    title = "Η Κοιλιά της Αρκούδας"
    weight = 2
    contentDir = "content/gr"

